services:
  mosquitto:
    image: eclipse-mosquitto
    container_name: mosquitto
    ports:
      - "1883:1883"
    volumes:
      - mosquitto-config-volume:/mosquitto/config
      - mosquitto-data-volume:/mosquitto/data
      - mosquitto-log-volume:/mosquitto/log
    environment:
      - MQTT_USER=${MQTT_USER}
      - MQTT_PASSWORD=${MQTT_PASSWORD}
    healthcheck:
      test: ["CMD", "mosquitto_sub", "-u", "${MQTT_USER}", "-P", "${MQTT_PASSWORD}", "-h", "localhost", "-t", "#", "-C", "1"]
      interval: 30s
      timeout: 10s
      retries: 3

volumes:
  mosquitto-config-volume:
    external: true
  mosquitto-data-volume:
    external: true
  mosquitto-log-volume:
    external: true
